apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: configservice
  name: configservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configservice
  template:
    metadata:
      labels:
        app: configservice
    spec:
      containers:
      - name: configservice
        image: quay.io/burrsutter/configuration-service-q-jvm:1.0.0
        ports:
          - containerPort: 8080
        env:
        - name: QUARKUS_HTTP_PORT
          value: '8080'
